POST http://localhost:8080/article

{
    "title": "a",
    "contents": "b",
    "user_name": "c"
}

###
GET http://localhost:8080/article/list


###
GET http://localhost:8080/article/1

###
POST http://localhost:8080/article/nice

{
    "article_id": 1,
    "title": "firstPost",
    "contents": "This is my first blog",
    "user_name": "saki"
}

###
POST http://localhost:8080/comment

{
    "article_id": 1,
    "message": "b"
}
